### ISSUE TITLE
Wrong convert

### ISSUE THREAD

**Issue by mrThomasTeller** [jansav/to-es6-template-literal#1]
Converts
`performance.now() + ' session lock in ' + sessionKeepTime.toFixed(2) + ' m'`
to
`${performance.now() + ' session lock in '}${sessionKeepTime.toFixed(2)} m`
Expected result is
`${performance.now()} session lock in ${sessionKeepTime.toFixed(2)} m`

**Comment by jansav** [comment]
Hi. It seems that the current implementation of https://www.npmjs.com/package/templatize-string doesn't support this. When I have enough time, I will replace the usage of that library with something better.

**Comment by jansav** [comment]
This should be fixed now.
