### ISSUE TITLE
Fails on basic conversion

### ISSUE THREAD

**Issue by gavinbarron** [jansav/to-es6-template-literal#2]
Input: 'Attempted to hit the endpoint: (' + contentPersonalizationResource + ') but encountered an error'
Expected: `Attempted to hit the endpoint: (${contentPersonalizationResource}) but encountered an error`
Actual: `Attempted to hit the endpoint: (' + contentPersonalizationResourc) but encountered an error`

**Comment by jansav** [comment]
Hi. It seems that the current implementation of https://www.npmjs.com/package/templatize-string doesn't support this. When I have enough time, I will replace the usage of that library with something better.

**Comment by jansav** [comment]
This should be fixed now.
